language: python

python:
  - 3.7

install:
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate
  - python manage.py collectstatic --noinput

script:
  - black --check .
  - flake8 .
  - coverage run --source=mysite_swe1_app,polls manage.py test

after_script:
  - coveralls
#rvm:
# - 2.2
deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "Encrypted <access-key-id>=AKIAXYKJVI5ALU2PPPTX"
  secret_access_key:
    secure: "Encypted <secret-access-key>=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"
  region: "us-west-2"
  app: "django"
  env: "django-env"
  bucket_name: "the-target-S3-bucket"